spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver

spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  port: 8888
  servlet:
    context-path: /api

cors:
  originPatterns: http://localhost:4200