spring:
  application:
    name: WS2
    version: v1.0.0-BETA
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/bd_ws2
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

cors:
  originPatterns: http://localhost:4200