spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bd_ws2}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

cors:
  originPatterns: ${CORS_ORIGIN:https://raphaelmun1z.github.io}